# Generated by Django 4.2.7 on 2023-11-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0002_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admindb',
        ),
    ]
