# Generated by Django 4.2.7 on 2023-12-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0004_rename_admindb_adminlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emplyoee',
            new_name='employee',
        ),
    ]
